### ISSUE TITLE
python setup.py syntax error

### ISSUE THREAD

**Issue by smrst** [complexpotato/Faitagram#107]
hi , 
why when try to run python setup.py i get this error ?
python setup.py
  File "setup.py", line 42
    chmod +x faitagram && chmod +x setup.py
                     ^
SyntaxError: invalid syntax

**Comment by TooPrecise** [comment]
same here, also when I try to: python faitagram the output is:

root@--:~/Faitagram# python faitagram
  File "faitagram", line 263
    python setup.py
               ^
SyntaxError: invalid syntax

**Comment by TooPrecise** [comment]
Ok, found the Issue.

There is an Error ion the setup.py file that needs to be corrected.

Line 42 which is the last one in the file looks like this:

os.system("wget https://github.com/mozilla/geckodriver/releases/download/v0.{}.{}/geckodriver-v0.{}.{}-linux{}.tar.gz".format(first,second,first,second,OS_bit))
os.system("tar -xvzf geckodriver-v0.{}.{}-linux{}.tar.gz".format(first,second,OS_bit))
os.system("rm geckodriver-v0.{}.{}-linux{}.tar.gz".format(first,second,OS_bit))
os.system("chmod +x geckodriver")
os.system("mv geckodriver /usr/local/bin/")

> chmod +x faitagram && chmod +x setup.py

But it has to look like this:

> os.system ("chmod +x faitagram && chmod +x setup.py")

**Comment by smrst** [comment]
thank you , yes it worked for me . 
now its another problem : 
here is the code : 
- Bruteforce starting ( Delay = 1 sec ) -

  Password: 123456 	| Failed 	| IP : 00 . 00 . 00. 00
 

**_Error : 0x01: General SOCKS server failure_**
i have checked tor , its running and listening .

**Comment by neetesshhr** [comment]
python setup.py
  File "setup.py", line 43
    os.system ("chmod +x faitagram && chmod +x setup.py")
    ^
IndentationError: unexpected indent

**Comment by neetesshhr** [comment]
python faitagram -s facebook -u MeMeBigBoy@gmail.com -w /root/passwd.txt -d 10
  File "faitagram", line 263
    python setup.py
               ^
SyntaxError: invalid syntax

**Comment by RXTE** [comment]
Yes, this Script has a lot of errors and I could use the time correcting it just building a better one.

So there is no use in trying to make this one work.

Besides if you have no idea what you are doing and are irritated by the simple python script not printing correctly you should do your homework first and foremost.

**Comment by neetesshhr** [comment]
while installing i got a error like this...

Warning: An abstract unix socket for session D-BUS might still be available. Use --net or remove unix from --protocol set.
Post-exec seccomp protector enabled
Child process initialized in 234.59 ms

Parent is shutting down, bye...
Traceback (most recent call last):
  File "setup.py", line 37, in <module>
    os.system("wget https://github.com/mozilla/geckodriver/releases/download/v0.{}.{}/geckodriver-v0.{}.{}-linux{}.tar.gz".format(first,second,first,second,OS_bit))
NameError: name 'OS_bit' is not defined

**Comment by smrst** [comment]
as i read about it online , The server was listening on 'localhost' which meant only on the localhost interface.
Not the external-facing network. thats why the ip doesnt change and its not working . i tried different links and codes and none actually worked . its still open . . .

**Comment by Anonymous118** [comment]
Can u fix this script

**Comment by iRahuln** [comment]
file "setup.py" line 37
OS_bit is not defined

**Comment by ArjunMenon-96** [comment]
a = 79
 
FirefoxVersion = int(a)
second = 0

if FirefoxVersion > 54:
	first = 19
OS_bit = 64

@RA-bit-del
