### ISSUE TITLE
Python cant open faitgram

### ISSUE THREAD

**Issue by JamesLDYT** [complexpotato/Faitagram#111]
When I run the command it said python: can't open file 'faitgram': [Errno 2] No such file or directory

I am using Lynux Ubuntu. please help

**Comment by psykofana** [comment]
Hi ! When you run the command, are you sure that you are in the faitagram directory ? 
I don't know if Ubuntu change anything but i'm in Kali ^^"

**Comment by JamesLDYT** [comment]
Im in the directory and just to check I tried in Kali and it did the same thing
