### ISSUE TITLE
python faitagram -s facebook -u MeMeBigBoy@gmail.com -w /root/passwd.txt -d 10

### ISSUE THREAD

**Issue by GhostAgent47** [complexpotato/Faitagram#115]
python faitagram -s facebook -u MeMeBigBoy@gmail.com -w /root/passwd.txt -d 10
  File "faitagram", line 263
    python setup.py
               ^
SyntaxError: invalid syntax

_Originally posted by @neetesshhr in https://github.com/Juniorn1003/Faitagram/issues/107#issuecomment-429950027_

**Comment by atik342** [comment]
I have also the same problem.Please let me know if anyone has solved this problem

**Comment by ArjunMenon-96** [comment]
os.system("python setup.py")


error will be fixed @atik342 @GhostAgent47
