### ISSUE TITLE
OS_bit is not defined

### ISSUE THREAD

**Issue by OgPlush** [complexpotato/Faitagram#117]
Hi,
When I run: `python setup.py`, after few seconds of installation, I have the following error:

`Traceback (most recent call last):
  File "setup.py", line 37, in <module>
    os.system("wget https://github.com/mozilla/geckodriver/releases/download/v0.{}.{}/geckodriver-v0.{}.{}-linux{}.tar.gz".format(first,second,first,second,OS_bit))
NameError: name 'OS_bit' is not defined`

If someone could help me solve it I would be really thankfull

**Comment by yesimxev** [comment]
You can simply replace the line with the appropiate arch source, as I did:
```
os.system("wget https://github.com/mozilla/geckodriver/releases/download/v0.21.0/geckodriver-v0.21.0-arm7hf.tar.gz")
os.system("tar -xvzf geckodriver-v0.21.0-arm7hf.tar.gz")
#os.system("rm geckodriver-v0.21.0-arm7hf.tar.gz"))
```
There are already recent versions, I had to use v0.21 for armhf

**Comment by dev902** [comment]
```
Traceback (most recent call last):
File "setup.py", line 40, in <module>
os.system("tar -xvzf geckodriver-v0.{}.{}-linux{}.tar.gz".format(first,second,OS_bit))
NameError: name 'OS_bit' is not defined
```

 I Am Facing This Error Can Anyone Help Me Out !!

**Comment by yesimxev** [comment]
@dev902 as above

**Comment by thistleknot** [comment]
$https://www.tecmint.com/find-out-linux-system-is-32-bit-or-64-bit/
OS_bit=$(dpkg --print-architecture)
echo $OS_bit

put that in the top of your script

**Comment by jisjose98** [comment]
remove python setup.py last line of faitagram coding
