### ISSUE TITLE
i followed all steps and I am getting this error

### ISSUE THREAD

**Issue by JorgeEscasan** [complexpotato/Faitagram#96]
![image](https://user-images.githubusercontent.com/14794885/43337688-720f32d8-9189-11e8-921c-4ca2c504bf26.png)

![image](https://user-images.githubusercontent.com/14794885/42838731-69c7ee06-89b6-11e8-8121-e7c29b9b9d0a.png)

**Comment by theRat336** [comment]
i'm a beginner in hacking but i think you would hide the IP

**Comment by JorgeEscasan** [comment]
true my bad, fixing rn
