### ISSUE TITLE
What can I do if this error is,but I follow the steps

### ISSUE THREAD

**Issue by MaHeShSoN** [complexpotato/Faitagram#97]
$ cd Faitagram
$ ls
LICENSE    faitagram  tmp
README.md  setup.py   wlist
$ python setup.py
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    OS_bit = (round(math.log(sys.maxint,2)+1))  # get the bit
AttributeError: module 'sys' has no attribute 'maxint'
$

**Comment by lisa34417** [comment]
Same problem here
